# https://decapcms.org/docs/backends-overview/
backend:
  name: git-gateway
  branch: main
  cms_label_prefix: decap-cms

publish_mode: editorial_workflow
display_url: https://popnc-ph.netlify.app/
media_folder: "docs/.vuepress/public/media"
public_folder: "/media"
editor:
  preview: false

collections:
  - name: "grammar"
    label: "Grammar Topics"
    label_singular: "Grammar Topic"
    folder: "docs/grammar"
    nested:
      depth: 2
    create: true
    slug: "{{slug}}/index"
    summary: "{{dirname}} . Last updated at {{commit_date}}"
    preview_path: grammar/{{slug}}
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Last Updated",
          name: "lastUpdated",
          widget: "hidden",
          default: true,
        }
      - {
          label: "Show Contributors",
          hint: "Show contributors at the footer",
          name: "contributors",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Show Icon for External Links",
          name: "externalLinkIcon",
          widget: "boolean",
          default: false,
        }
      - label: "Entry Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        time_format: false
        required: true
      # - {
      #     label: "Grammar Type",
      #     name: "grammar_type",
      #     widget: "select",
      #     options:
      #       [
      #         "Parts of Speech",
      #         "Sentence Structure",
      #         "Tenses",
      #         "Subject-Verb Agreement",
      #         "Modal Verbs",
      #         "Active vs Passive Voice",
      #         "Direct and Indirect Speech",
      #         "Other",
      #       ],
      #   }
      # - {
      #     label: "Meme Image",
      #     name: "meme_image",
      #     widget: "image",
      #     required: false,
      #   }
      # - {
      #     label: "Meme Type",
      #     name: "meme_type",
      #     widget: "select",
      #     options: ["social media", "mass media", "other media"],
      #     required: false,
      #   }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          default: "# Grammar Topic Title",
        }
